sudo: false
dist: trusty
language: java
jdk: oraclejdk8

script: "mvn cobertura:cobertura"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/57219697b0fbfc906418
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - "target/perworldinventory-kt-2.3.1.jar"
  on:
    tags: true

